# Generated by Django 5.2.5 on 2025-10-25 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_uid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('registration_number', models.CharField(max_length=20)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('MINIVAN', 'Minivan'), ('ROADSTER', 'Roadster')], max_length=20)),
                ('availability', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cars',
                'indexes': [models.Index(fields=['availability'], name='cars_availab_ce8337_idx'), models.Index(fields=['brand', 'model'], name='cars_brand_78f303_idx')],
            },
        ),
    ]
